@echo off
echo Regenerating Prisma Client...
echo.
echo Step 1: Stopping any running processes...
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul

echo Step 2: Generating Prisma Client...
call npx prisma generate

echo.
echo Step 3: Starting dev server...
call npm run dev
